### ISSUE TITLE
One SQL query for calculating tags

### ISSUE THREAD

**Issue by galetahub** [Faulik/ruby_rails_expl#1]
Тут виходить скільки тегів - скільки запитів в БД генерить код - так є not good.
Давай підрахунок тегів зробимо одним запитом в БД
https://github.com/Faulik/ruby_rails_expl/blob/master/app/controllers/welcome_controller.rb#L13

**Comment by Faulik** [comment]
У два запити можу, в один поки що ні.
https://github.com/Faulik/ruby_rails_expl/commit/11a0116cd4464e6e4bad9aa8a8350a8a65fa17d0
